repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2 # v0.16.1
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: local
  hooks:
    - id: ty
      name: ty
      entry: uv run ty check
      language: system
      types: [python]
      pass_filenames: false
