repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56 # v0.15.20
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: local
  hooks:
    - id: ty
      name: ty
      entry: uv run ty check
      language: system
      types: [python]
      pass_filenames: false
